title: Precision Health Research, Singapore (PRECISE)
url: https://npm.sg
favicon: /images/Logos/favicon.png
colors:
  primary-color: "#584199"
  secondary-color: "#bb2029"
  media-colors:
    - title: media-color-one
      color: "#213966"
    - title: media-color-two
      color: "#5e7597"
    - title: media-color-three
      color: "#bddda1"
    - title: media-color-four
      color: "#5ec2ac"
    - title: media-color-five
      color: "#213966"
description: Precision Health Research, Singapore (PRECISE) is the central
  entity set up to coordinate a whole-of-government effort to implement Phase 2
  of Singaporeâ€™s National Precision Medicine (NPM) programme.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.dqnzptkrohwji.amplifyapp.com
prod: https://master.dqnzptkrohwji.amplifyapp.com
facebook-pixel: ""
shareicon: /images/Logos/1_Email_Signature_Logo_10cm_72dpi.png
is_government: false
google_analytics: ""
google_analytics_ga4: G-F4BEQT87XS
linkedin-insights: ""
resources_name: news-and-highlights
